### ISSUE TITLE
Question about the tokenizer

### ISSUE THREAD

**Issue by IshootLaser** [longyuewangdcu/Chinese-Llama-2#10]
Hello! It is very nice that you adapt Llama 2 for Chinese language and got great result.
I am new to LLM, and I wonder how to get the tokenizer for Llama 2? If I remember correctly, Llama 2 does not offically support Chinese, and the official model only have a couple hunderds of Chinese characters in its tokenizer.
Any explanation will be greatly appreciated, thanks!

**Comment by seeledu** [comment]
Llama2 uses BPE, for words not in the dictionary, it will cut them into bytes.
