### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by XiongKexin** [longyuewangdcu/Chinese-Llama-2#2]
When I run test/inference.py, there is an error "NotImplementedError: Cannot copy out of meta tensor; no data!". I don't know how to fix it. Is this due to my wrong transformer version(4.29.0)?

```
[2023-07-24 05:20:38,101] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]python-BaseException
Loading checkpoint shards:   0%|          | 0/2 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/data/kexin/anaconda3/envs/cllama2/lib/python3.8/site-packages/accelerate/utils/modeling.py" line 149, in set_module_tensor_to_device
    new_value = value.to(device)
NotImplementedError: Cannot copy out of meta tensor; no data!

Process finished with exit code 143
```

**Comment by seeledu** [comment]
Can you post the bash command you used here? It seems that the path of your model path or data path are not set correctly. BTW， Please comment out the push_to_hub part in line 140 of the inference.py code, I have tested it and it can infer.

**Comment by XiongKexin** [comment]
> Can you post the bash command you used here? It seems that the path of your model path or data path are not set correctly. BTW， Please comment out the push_to_hub part in line 140 of the inference.py code, I have tested it and it can infer.

Sure. My bash cmd is
```
python test/inference.py --model-name-or-path
/data/kexin/downloads/Chinese-Llama-2-7B/
-t
0.7
-sa
'sample'
-i
/data/kexin/project/chinese-llama-2/test/test_case.txt
-o
/data/kexin/project/chinese-llama-2/test/test_case.general-task.txt

```
And I located the code that raised this error. It's line 137:
```
136    # Load checkpoints
137    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, torch_dtype=torch.bfloat16, device_map="auto")
138    #, offload_folder="offload",offload_state_dict = True,    
```

**Comment by seeledu** [comment]
It seems that your model weight has not been fully downloaded. You can check the sizes of the two model files under the /data/kexin/downloads/Chinese-Llama-2-7B/ path, and compare them with those at https://huggingface.co/seeledu/Chinese-Llama-2-7B/tree/main.

**Comment by XiongKexin** [comment]
> It seems that your model weight has not been fully downloaded. You can check the sizes of the two model files under the /data/kexin/downloads/Chinese-Llama-2-7B/ path, and compare them with those at https://huggingface.co/seeledu/Chinese-Llama-2-7B/tree/main.

Thank you. I'll re-download the model files and try again.

**Comment by seeledu** [comment]
ok, if you have any other questions, you can open another issue to discuss.

**Comment by XiongKexin** [comment]
> ok, if you have any other questions, you can open another issue to discuss.

I re-download the model files but still got this error 
```
[2023-07-24 06:38:46,649] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]python-BaseException
Loading checkpoint shards:   0%|          | 0/2 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/data/kexin/anaconda3/envs/cllama2/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 149, in set_module_tensor_to_device
    new_value = value.to(device)
NotImplementedError: Cannot copy out of meta tensor; no data!

Process finished with exit code 143
```
