### ISSUE TITLE
Re-dowloaded model files, still got the "no data" error

### ISSUE THREAD

**Issue by XiongKexin** [longyuewangdcu/Chinese-Llama-2#3]
> ok, if you have any other questions, you can open another issue to discuss.

Sorry, but I re-download the model files and still got the same error 
```
[2023-07-24 06:38:46,649] [INFO] [real_accelerator.py:133:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]python-BaseException
Loading checkpoint shards:   0%|          | 0/2 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "/data/kexin/anaconda3/envs/cllama2/lib/python3.8/site-packages/accelerate/utils/modeling.py", line 149, in set_module_tensor_to_device
    new_value = value.to(device)
NotImplementedError: Cannot copy out of meta tensor; no data!

Process finished with exit code 143
```

_Originally posted by @XiongKexin in https://github.com/longyuewangdcu/Chinese-Llama-2/issues/2#issuecomment-1647305638_

**Comment by seeledu** [comment]
I have pushed the transformer we used for this project. You can use it by the command "pip install -e <path to the transformers>" :)

**Comment by seeledu** [comment]
if you have any other questions, you can open another issue or send me an email at mc05583@umac.mo to discuss.

**Comment by XiongKexin** [comment]
> if you have any other questions, you can open another issue or send me an email at [mc05583@umac.mo](mailto:mc05583@umac.mo) to discuss.

Thank you very much! The error disappeared after I changed the model I use from huggingface one to the baiduyun one.
