### ISSUE TITLE
Fine tuning

### ISSUE THREAD

**Issue by qyaaang** [longyuewangdcu/Chinese-Llama-2#7]
I'm running the bash script to fine-tune the model and get the following error message:

[W socket.cpp:601] [c10d] The client socket has failed to connect to [localhost]:29500 (errno: 99 - Cannot assign requested address).

Could you please check that?

**Comment by seeledu** [comment]
if you use a single node， the master node address MASTER_ADDR should change to 127.0.0.1 and HOST_NUM=1

**Comment by qyaaang** [comment]
Thanks for your reply. It looks like this issue is resolved now.

**Comment by qyaaang** [comment]
I got another error message as follows.

ValueError: Your setup doesn't support bf16/gpu. You need torch>=1.10, using Ampere GPU with cuda>=11.0.

Currently, I'm trying to run code on a single NVIDIA V100 GPU, which is a Volta architecture. Should I use an Ampere GPU like RTX 2080?

Thanks for your time.

**Comment by seeledu** [comment]
yep, you can try to use fp16 for V100(change the config in the train.sh and deepspeed.config) or use an Ampere GPU
