### ISSUE TITLE
the model download from https://huggingface.co/seeledu/Chinese-Llama-2-7B can no be used

### ISSUE THREAD

**Issue by 3244we** [longyuewangdcu/Chinese-Llama-2#8]
Loading checkpoint shards:   0%|                                                                                                                                                                                      | 0/2 [01:33<?, ?it/s]
Traceback (most recent call last):
  File "/home/chenjunhao/chinese-llama-2/test/inference.py", line 137, in <module>
    model = AutoModelForCausalLM.from_pretrained(model_name_or_path, torch_dtype=torch.bfloat16, device_map="auto")
  File "/home/chenjunhao/chinese-llama-2/transformers/src/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/chenjunhao/chinese-llama-2/transformers/src/transformers/modeling_utils.py", line 2643, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/chenjunhao/chinese-llama-2/transformers/src/transformers/modeling_utils.py", line 2966, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/chenjunhao/chinese-llama-2/transformers/src/transformers/modeling_utils.py", line 671, in _load_state_dict_into_meta_model
    set_module_tensor_to_device(model, param_name, param_device, **set_module_kwargs)
  File "/home/chenjunhao/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 149, in set_module_tensor_to_device
    new_value = value.to(device)
NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by 3244we** [comment]
my sh file

# Multi-nodes are also supported

export NCCL_DEBUG=INFO
export NCCL_SOCKET_IFNAME=eno1,docker0,eno2,ens8f0
export NCCL_IB_GID_INDEX=3
export NCCL_IB_SL=3
export NCCL_NET_GDR_READ=1

export MASTER_ADDR="${CHIEF_IP:=localhost}"
export MASTER_PORT="${MASTER_PORT:=5202}"

export INDEX=0

path=xxx
train_path=xxx

model_path=xxx
model_save=xxx

torchrun --nnodes 1 --node_rank $INDEX --nproc_per_node 1 \
  --master_addr $MASTER_ADDR --master_port $MASTER_PORT  \
  ${train_path} \
  --deepspeed xxx/train/deepspeed_config_bf16.json \
  --model_name_or_path ${model_path} \
  --train_file xxx/data/instruction/example_instruction_hf.json \
  --validation_file xxx/data/instruction/example_instruction_hf_dev.json \
  --preprocessing_num_workers 32 \
  --dataloader_num_workers 16 \
  --dataloader_pin_memory True \
  --per_device_train_batch_size 1 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --num_train_epochs 3 \
  --save_strategy "steps" \
  --save_steps 500 \
  --save_total_limit 1 \
  --learning_rate 2e-5 \
  --weight_decay 0. \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 10 \
  --block_size 866 \
  --use_lora True \
  --lora_config $path/train/lora_config.json \
  --do_train \
  --bf16 True \
  --bf16_full_eval True \
  --evaluation_strategy "no" \
  --validation_split_percentage 0 \
  --streaming \
  --ddp_timeout 72000 \
  --seed 1 \
  --overwrite_output_dir\
  --gradient_checkpointing True \
  --output_dir ${model_save}

**Comment by seeledu** [comment]
If you're using a model with full parameters, use a script that corresponds to  full weights. It looks like the command you posted is for lora inference. （ --use_lora True

**Comment by 3244we** [comment]
> 

我想要在你微调后的模型上做lora微调，直接用你的参数可以吗，这个模型推理的时候好像也load不进去

**Comment by 3244we** [comment]
命令都是用你的md上面的

**Comment by 3244we** [comment]
> 

用的就是这个仓库里面的transformer

**Comment by boyaxxx** [comment]
也遇到了同样的问题

`RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        While copying the parameter named "layers.15.self_attn.q_proj.weight", whose dimensions in the model are torch.Size([4096, 4096]) and whose dimensions in the 
checkpoint are torch.Size([4096, 4096]), an exception occurred : ('Cannot copy out of meta tensor; no data!',).
        While copying the parameter named "layers.15.self_attn.k_proj.weight", whose dimensions in the model are torch.Size([4096, 4096]) and whose dimensions in the 
checkpoint are torch.Size([4096, 4096]), an exception occurred : ('Cannot copy out of meta tensor; no data!',).
        While copying the parameter named "layers.15.self_attn.v_proj.weight", whose dimensions in the model are torch.Size([4096, 4096]) and whose dimensions in the 
checkpoint are torch.Size([4096, 4096]), an exception occurred : ('Cannot copy out of meta tensor; no data!',).
`

**Comment by seeledu** [comment]
似乎是我推到huggingface的版本有问题，请先使用百度网盘的版本，我更新下huggingface仓库上的模型
